# Configuration for Alacritty, the GPU enhanced terminal emulator

window:
  # Window dimensions in character columns and lines
  # Falls back to size specified by window manager if set to 0x0.
  # (changes require restart)
  dimensions:
    columns: 120
    lines: 36

  # Adds this many blank pixels of padding around the window
  # Units are physical pixels; this is not DPI aware.
  # (change requires restart)
  padding:
    x: 2
    y: 2

font:
  normal:
    family: 'Bitstream Vera Sans Mono'

  # Point size of the font
  size: 9.0

# Background opacity
background_opacity: 0.8
