#!/usr/bin/env bash
set -euo pipefail

HOOK_DIR="${0%/*}/../"
source "${HOOK_DIR}/lib/base.sh"
trap -- '__cleanup_temp' EXIT

install-asdf-plugins() {
  local asdf existing_plugins

  if [ $# -lt 1 ]; then
    return 0
  fi

  asdf="${HOME}/.asdf/bin/asdf"
  existing_plugins="$("${asdf}" plugin list)"

  for plugin in "$@"; do
    if ! grep -Fe "$plugin" <<<"$existing_plugins" &>/dev/null; then
      "$asdf" plugin add "$plugin"
    fi
  done
}

if [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
  printf '%s\n' '-------------------------------------------------------'
  __message 'Generic Tools Manager (asdf-vm)'
  printf '%s\n' '-------------------------------------------------------'

  if ! [ -e "${HOME}/.asdf" ]; then
    command git clone https://github.com/asdf-vm/asdf.git "${HOME}/.asdf"
    pushd "${HOME}/.asdf" &>/dev/null
    command git checkout "$(command git describe --abbrev=0 --tags)"
    popd &>/dev/null
  fi

  if [ -x "${HOME}/.asdf/bin/asdf" ]; then
    "${HOME}/.asdf/bin/asdf" update
  fi

  if [ -e "${HOME}/.asdf/asdf.sh" ]; then
    . "${HOME}/.asdf/asdf.sh"

    install-asdf-plugins \
      python \
      golang \
      ruby \
      nodejs \
      boundary \
      consul \
      nomad \
      packer \
      terraform \
      vault \
      waypoint \
      kubectl \
      tfsec \
      helm \
      gohugo
  fi
fi
