#!/usr/bin/env bash
set -euo pipefail

HOOK_DIR="${0%/*}/../"
source "${HOOK_DIR}/lib/base.sh"

__install_nodenv() {
  set-git-repo "${HOME}/.nodenv" https://github.com/nodenv/nodenv.git 'Nodenv'

  if ! command -v nodenv &>/dev/null; then
    touch "${HOME}/.path.local"

    if ! printf '%s\n' "$PATH" | grep -qFe '/.nodenv/bin' &>/dev/null && ! grep -qFe '/.nodenv/bin' "${HOME}/.path.local"; then
      printf 'PATH="%s"\n' "\${HOME}/.nodenv/bin:\${PATH}" >> "${HOME}/.path.local"
      __message 'Nodenv has been added to your PATH. Please reload the shell session'
    fi
  fi
}

__install_nodenv_plugin() {
  local name repo nodenv base_dir
  repo="$1"; shift
  if [ $# -gt 0 ]; then
    name="$1"; shift
  else
    name="$(basename -s .git -- "$repo")"
  fi
  nodenv="$(__get_cmd nodenv "${HOME}/.nodenv/bin/nodenv")"
  base_dir="$("$nodenv" root)/plugins/$name"

  set-git-repo "$base_dir" "$repo" "$name"
}

__install_node() {
  local nodenv version
  version="$1"; shift
  nodenv="$(__get_cmd nodenv "${HOME}/.nodenv/bin/nodenv")"

  if [ ! -e "${HOME}/.nodenv/versions/${version}" ]; then
    __message "Installing v${version} of NodeJS"
    "$nodenv" install "$version"
  else
    __message "NodeJS v${version} is already installed"
  fi
}

__set_node_bin() {
  local nodenv version
  version="$1"; shift
  nodenv="$(__get_cmd nodenv "${HOME}/.nodenv/bin/nodenv")"

  "$nodenv" global "$version"
}

if [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
  printf '%s\n' '-------------------------------------------------------'
  __message 'Node version manager (nodenv)'
  printf '%s\n' '-------------------------------------------------------'

  __install_nodenv
  __install_nodenv_plugin 'https://github.com/nodenv/node-build.git'
  __install_nodenv_plugin 'https://github.com/nodenv/node-build-update-defs.git'
  __install_nodenv_plugin 'https://github.com/nodenv/nodenv-update.git'
  __install_node '12.14.0'
  __set_node_bin '12.14.0'
fi
