#!/bin/bash
set -e

cat <<MSG
--------------------
>>  Rust version manager (rustup)
--------------------
MSG

if [ -e "$HOME/.cargo/bin" ] && ! (echo "$PATH" | grep -q "$HOME/.cargo/bin"); then
  echo '~/.cargo/bin exists, but is not in your PATH' >&2
fi

if ! command -v rustup &>/dev/null; then
  if [ -x "${HOME}/.cargo/bin/rustup" ]; then
    echo "Skipping \`rustup' installation because it already exists in ~/.cargo/bin ..." >&2
  else
    curl -sSLo /tmp/rustup-init.sh https://sh.rustup.rs
    sh /tmp/rustup-init.sh --no-modify-path -y
  fi
else
  rustup self update
fi

if ! command -v rustc &>/dev/null; then
  if [ -x "${HOME}/.cargo/bin/rustc" ]; then
    echo "Skipping \`rustc' installation because it already exists in ~/.cargo/bin ..." >&2
  else
    rustup install stable
  fi
else
  rustup update stable
fi

cat <<MSG
--------------------
>>  Done.
--------------------
MSG
