#!/bin/bash
source "/usr/local/share/chruby/chruby.sh"
set -euo pipefail

RUBY_INSTALL_SRC_DIR="${HOME}/.ruby-install/src"

__message() {
  printf '>>  %s\n' "$*"
}

__error() {
  __message "$*" >&2
}

__fatal() {
  __error "$*"
  exit 1
}

__ensure_ruby_source_dir() {
  if [ -z "$RUBY_INSTALL_SRC_DIR" ]; then
    return 1
  fi

  if [ ! -d "$RUBY_INSTALL_SRC_DIR" ]; then
    mkdir -p "$RUBY_INSTALL_SRC_DIR"
  fi
}

__latest_installed_ruby() {
  __list_ruby_versions | grep -e 'ruby-' | sort | tail -n 1
}

__list_ruby_versions() {
  for dir in "${HOME}"/.rubies/*; do
    printf '%s\n' "$(basename "$dir")"
  done
}

__set_default_ruby() {
  printf '%s\n' "$1" > "${HOME}/.ruby-version"
}

__get_default_ruby() {
  if [ -f "${HOME}/.ruby-version" ]; then
    head -n 1 "${HOME}/.ruby-version"
  else
    __latest_installed_ruby
  fi
}

__ensure_default_ruby_is_set() {
  __set_default_ruby "$(__get_default_ruby)"
}

__is_ruby_version_installed() {
  local version_string
  version_string="$1"

  if __list_ruby_versions | grep -qF -e "$version_string" &>/dev/null; then
    return 0
  else
    return 1
  fi
}

__ensure_default_ruby_is_installed() {
  local ruby_version_string ruby_type ruby_version

  touch "${HOME}/.ruby-version"

  ruby_version_string=$(__get_default_ruby)

  if __is_ruby_version_installed "$ruby_version_string"; then
    ruby_type="${ruby_version_string%%-*}"
    if [ -z "$ruby_type" ]; then ruby_type='ruby'; fi
    ruby_version="${ruby_version_string#*-}"

    __message "Installing default Ruby (${ruby_version_string})"
    command ruby-install --src-dir "${RUBY_INSTALL_SRC_DIR}" --latest --cleanup "$ruby_type" "$ruby_version"
  fi

  if type chruby &>/dev/null; then
    chruby "$ruby_version_string"
  fi
}


if [ "${BASH_SOURCE[0]}" = "$0" ]; then
  printf '%s\n' '--------------------'
  __message 'Ruby installer'
  printf '%s\n' '--------------------'

  if command -v ruby-install &>/dev/null; then
    __ensure_ruby_source_dir
    __ensure_default_ruby_is_installed
    __ensure_default_ruby_is_set
  fi

  printf '%s\n' '--------------------'
  __message 'Done'
  printf '%s\n' '--------------------'
fi
