#!/bin/bash
source "/usr/local/share/chruby/chruby.sh"
set -euo pipefail

RUBY_INSTALL_SRC_DIR="${HOME}/.ruby-install/src"

__message() {
  printf '>>  %s\n' "$*"
}

__error() {
  __message "$*" >&2
}

__fatal() {
  __error "$*"
  exit 1
}

__ensure_ruby_source_dir() {
  if [ -z "$RUBY_INSTALL_SRC_DIR" ]; then
    return 1
  fi

  if [ ! -d "$RUBY_INSTALL_SRC_DIR" ]; then
    mkdir -p "$RUBY_INSTALL_SRC_DIR"
  fi
}

__latest_installed_ruby() {
  __list_ruby_versions | grep -e 'ruby-' | sort | tail -n 1
}

__list_ruby_versions() {
  for dir in "${HOME}/.rubies/*"; do
    printf '%s\n' "$(basename "$dir")"
  done
}

__set_default_ruby() {
  printf '%s\n' "$1" > "${HOME}/.ruby-version"
}

__get_default_ruby() {
  if [ -f "${HOME}/.ruby-version" ]; then
    head -n 1 "${HOME}/.ruby-version"
  else
    __latest_installed_ruby
  fi
}

__ensure_default_ruby_is_set() {
  local ruby_version_string

  if [ -z "$(__get_default_ruby)" ]; then
    # Install the latest MRI if no ruby is installed or specified
    __message 'Installing the latest Ruby'
    command ruby-install --src-dir "${RUBY_INSTALL_SRC_DIR}" --latest ruby
  fi

  # ensure default ruby is persisted to ~/.ruby-version
  ruby_version_string=$(__get_default_ruby)
  __set_default_ruby "$ruby_version_string"
}

__ensure_default_ruby_is_installed() {
  local ruby_version_string ruby_type ruby_version

  ruby_version_string=$(__get_default_ruby)

  if __list_ruby_versions | grep -qF -e "$ruby_version_string" &>/dev/null; then
    ruby_type=${ruby_version_string%%-*}
    ruby_version=${ruby_version_string#*-}

    __message "Installing default Ruby (${ruby_version_string})"
    command ruby-install --src-dir "${RUBY_INSTALL_SRC_DIR}" "$ruby_type" "$ruby_version"
  fi

  if type chruby &>/dev/null; then
    chruby "$ruby_version_string"
  fi
}


if [ "${BASH_SOURCE[0]}" = "$0" ]; then
  printf '%s\n' '--------------------'
  __message 'Ruby installer'
  printf '%s\n' '--------------------'

  if command -v ruby-install &>/dev/null; then
    __ensure_ruby_source_dir
    __ensure_default_ruby_is_set
    __ensure_default_ruby_is_installed
  fi

  printf '%s\n' '--------------------'
  __message 'Done'
  printf '%s\n' '--------------------'
fi
