#!/bin/bash

if ! type chruby &>/dev/null; then
  # chruby might have just been installed on previous step. Use it.
  source "/usr/local/share/chruby/chruby.sh"
fi

set -eo pipefail

HOOK_DIR="${0%/*}/../"

__message() {
  printf '>>  %s\n' "$*"
}

__error() {
  __message "$*" >&2
}

__fatal() {
  __error "$*"
  exit 1
}

__md5_generate() {
  local file=$1
  openssl md5 "$file" | sed -e 's/MD5(.*)= //g'
}
__md5_verify() {
  local file=$1
  local checksumfile=${2:-"${file}.md5"}
  #echo "Verifying ${file} with ${checksumfile}"

  if diff -q <(__md5_generate "$file") <(cat "$checksumfile") &>/dev/null; then
    return 0
  else
    return 1
  fi
}
__verify_or_source() {
  local file="$1"
  local checksumfile="${file}.md5"

  if [ -f "$checksumfile" ] && __md5_verify "$file" "$checksumfile"; then
    return 0
  fi

  source "$file"

  __md5_generate "$file" > "$checksumfile"
}

__install_packages() {
  local package_manager
  package_manager="$1"; shift

  if [ -f "${HOOK_DIR}/packages/${package_manager}" ]; then
    __verify_or_source "${HOOK_DIR}/packages/${package_manager}"
  fi
}

__get_default_ruby() {
  if [ -f "${HOME}/.ruby-version" ]; then
    head -n 1 "${HOME}/.ruby-version"
  else
    __latest_installed_ruby
  fi
}

__list_ruby_versions() {
  for dir in "${HOME}"/.rubies/*; do
    printf '%s\n' "$(basename "$dir")"
  done
}

__latest_installed_ruby() {
  __list_ruby_versions | grep -e '^ruby-' | sort | tail -n 1
}

if [ "$(command -v ruby)" = "/usr/bin/ruby" ]; then
  # On first run, might be default /usr/bin/ruby requiring sudo for 'gem install'
  # We'll be using chruby moving forward anyway
  chruby "$(__get_default_ruby)"
fi

if [[ "${BASH_SOURCE[0]}" = "$0" ]] && command -v gem &>/dev/null; then
  printf '%s\n' '-------------------------------------------------------'
  __message 'Ruby package manager (gem)'
  printf '%s\n' '-------------------------------------------------------'

  __install_packages 'rubygems'
fi
