#!/bin/bash
set -e

cat <<MSG
--------------------
>>  Ruby package manager (gem)
--------------------
MSG

HOOK_DIR="${0%/*}/../"

function __md5_generate() {
  local file=$1
  openssl md5 "$file" | sed -e 's/MD5(.*)= //g'
}
function __md5_verify() {
  local file=$1
  local checksumfile=${2:-"${file}.md5"}
  #echo "Verifying ${file} with ${checksumfile}"

  if diff -q <(__md5_generate "$file") <(cat "$checksumfile") &>/dev/null; then
    return 0
  else
    return 1
  fi
}
function __verify_or_source() {
  local file="$1"
  local checksumfile="${file}.md5"

  if [ -f "$checksumfile" ] && __md5_verify "$file" "$checksumfile"; then
    return 0
  fi

  source "$file"

  __md5_generate "$file" > "$checksumfile"
}

if command -v gem &>/dev/null; then
  # TODO: Additional rubygems configurations?

  if [ -f "${HOOK_DIR}/packages/rubygems" ]; then
    __verify_or_source "${HOOK_DIR}/packages/rubygems"
  fi
fi

cat <<MSG
--------------------
>>  Done.
--------------------
MSG
