#!/bin/bash
set -euo pipefail

HOOK_DIR="${0%/*}/../"
source "${HOOK_DIR}/lib/base.sh"
trap -- '__cleanup_temp' EXIT

if [[ "${BASH_SOURCE[0]}" = "$0" ]] && command -v go &>/dev/null; then
  printf '%s\n' '-------------------------------------------------------'
  __message 'Go package manager'
  printf '%s\n' '-------------------------------------------------------'

  __install_packages 'go'
fi
