#!/bin/bash
set -euo pipefail

HOOK_DIR="${0%/*}/../"
source "${HOOK_DIR}/lib/base.sh"
trap -- '__cleanup_temp' EXIT

__set_npm_install_point() {
  local npm_packages_dir
  npm_packages_dir=${NPM_PACKAGES:-"${HOME}/.npm-packages"}

  npm config set prefix "${npm_packages_dir}"
}

__set_npm_bins_in_path() {
  local npm_packages_dir
  npm_packages_dir=${NPM_PACKAGES:-"${HOME}/.npm-packages"}
  if ! printf '%s' "$PATH" | grep -qFe "$npm_packages_dir" &>/dev/null; then
    export PATH="$PATH:${npm_packages_dir}/bin"
  fi
}

__set_python_interpreter() {
  # This is due to many npm packages requiring python to be installed for node-gyp to
  # do its thing. Since most of them still require python 2.x explicitly, that's what
  # we'll set here. Keep this updated to whatever is set for a python2.7 interpreter
  # in `hooks/pre-up/02_python_version_changer`
  npm config set python 'python2.7'
}


if [[ "${BASH_SOURCE[0]}" = "$0" ]] && command -v npm &>/dev/null; then
  printf '%s\n' '-------------------------------------------------------'
  __message 'Node package manager (npm)'
  printf '%s\n' '-------------------------------------------------------'

  __set_npm_bins_in_path
  __set_npm_install_point
  __set_python_interpreter
  __install_packages 'npm'
fi
