#!/bin/bash
set -euo pipefail

HOOK_DIR="${0%/*}/../"

__message() {
  printf '>>  %s\n' "$*"
}

__error() {
  __message "$*" >&2
}

__fatal() {
  __error "$*"
  exit 1
}

__md5_generate() {
  local file=$1
  openssl md5 "$file" | sed -e 's/MD5(.*)= //g'
}
__md5_verify() {
  local file=$1
  local checksumfile=${2:-"${file}.md5"}
  #echo "Verifying ${file} with ${checksumfile}"

  if diff -q <(__md5_generate "$file") <(cat "$checksumfile") &>/dev/null; then
    return 0
  else
    return 1
  fi
}
__verify_or_source() {
  local file="$1"
  local checksumfile="${file}.md5"

  if [ -f "$checksumfile" ] && __md5_verify "$file" "$checksumfile"; then
    return 0
  fi

  source "$file"

  __md5_generate "$file" > "$checksumfile"
}

__set_npm_install_point() {
  local npm_packages_dir
  npm_packages_dir=${NPM_PACKAGES:-"${HOME}/.npm-packages"}

  npm config set prefix "${npm_packages_dir}"
}

__set_npm_bins_in_path() {
  local npm_packages_dir
  npm_packages_dir=${NPM_PACKAGES:-"${HOME}/.npm-packages"}
  if ! printf '%s' "$PATH" | grep -qFe "$npm_packages_dir" &>/dev/null; then
    export PATH="$PATH:${npm_packages_dir}/bin"
  fi
}

__set_python_interpreter() {
  # This is due to many npm packages requiring python to be installed for node-gyp to
  # do its thing. Since most of them still require python 2.x explicitly, that's what
  # we'll set here. Keep this updated to whatever is set for a python2.7 interpreter
  # in `hooks/pre-up/02_python_version_changer`
  npm config set python "${HOME}/.pyenv/versions/2.7.15/bin/python2.7"
}

__install_packages() {
  local package_manager
  package_manager="$1"; shift

  if [ -f "${HOOK_DIR}/packages/${package_manager}" ]; then
    __verify_or_source "${HOOK_DIR}/packages/${package_manager}"
  fi
}


if [[ "${BASH_SOURCE[0]}" = "$0" ]] && command -v npm &>/dev/null; then
  printf '%s\n' '-------------------------------------------------------'
  __message 'Node package manager (npm)'
  printf '%s\n' '-------------------------------------------------------'

  __set_npm_bins_in_path
  __set_npm_install_point
  __set_python_interpreter
  __install_packages 'npm'
fi
