#!/bin/bash
set -euo pipefail

HOOK_DIR="${0%/*}/../"
source "${HOOK_DIR}/lib/base.sh"
trap -- '__cleanup_temp' EXIT

python3="${HOME}/.pyenv/shims/python3"

if [[ "${BASH_SOURCE[0]}" = "$0" ]] && [ -x "$python3" ]; then
  printf '%s\n' '-------------------------------------------------------'
  __message 'Python package manager (pip)'
  printf '%s\n' '-------------------------------------------------------'

  __install_packages 'pip'
fi
