#!/usr/bin/env bash
set -euo pipefail

HOOK_DIR="${0%/*}/../"
source "${HOOK_DIR}/lib/base.sh"
trap -- '__cleanup_temp' EXIT

__uninstall_instant_d() {
  rm -rf /usr/local/share/instant.d /usr/local/bin/instant.d
}

__install_instant_d() {
  local dl_url dl_file dl_dir version
  version="$1"; shift
  dl_dir=$(mktemp-dir)
  dl_url="https://github.com/thelonelyghost/insta.d/archive/v${version}.tar.gz"

  pushd "$dl_dir" &>/dev/null

  command curl -SLo ./archive.tgz "$dl_url"
  tar xzf ./archive.tgz --strip-components=1
  sudo make install

  popd &>/dev/null
}

__ensure_instant_d() {
  local version
  version="$1"; shift

  if [ ! -x '/usr/local/bin/instant.d' ] && [ ! -e '/usr/local/share/instant.d' ]; then
    __message 'Installing fresh copy of instant.d'
    __install_instant_d "$version"
  elif [ ! -x '/usr/local/bin/instant.d' ]; then
    __message 'Repairing instant.d installation'
    __uninstall_instant_d
    __install_instant_d "$version"
  elif [ ! -e '/usr/local/share/instant.d' ]; then
    __message 'Repairing instant.d installation'
    __uninstall_instant_d
    __install_instant_d "$version"
  elif ! grep -qFe 'VERSION="'"$version"'"' '/usr/local/share/instant.d/lib.sh' &>/dev/null; then
    __message 'Upgrading instant.d'
    __uninstall_instant_d
    __install_instant_d "$version"
  fi
}

if [[ "${BASH_SOURCE[0]}" = "$0" ]] && command -v curl &>/dev/null; then
  printf '%s\n' '-------------------------------------------------------'
  __message 'Instant.d (CLI)'
  printf '%s\n' '-------------------------------------------------------'

  __ensure_instant_d '0.1.3'
fi
