#!/bin/bash
set -e

if [ -t 2 ]; then
  fg_red=$'\e[31m'
  fg_bold_white=$'\e[1;37m'
  reset_color=$'\e[m'
else
  fg_red=""
  fg_bold_white=""
  reset_color=""
fi

function __md5_generate() {
  local file=$1
  ( md5sum <"$file"; test $? = 127 && md5 <"$file" ) | cut -d' ' -f1
}
function __md5_verify() {
  local file=$1
  local checksumfile=${2:-"${file}.md5"}
  #echo "Verifying ${file} with ${checksumfile}"

  if [ $(__md5_generate "$file") = $(cat "$checksumfile") ]; then
    return 0
  else
    return 1
  fi
}
function __verify_or_source() {
  local file="$1"
  local checksumfile="${file}.md5"

  if [ -f "$checksumfile" ] && __md5_verify "$file" "$checksumfile"; then
    return 0
  fi

  source "$file"

  __md5_generate "$file" > "$checksumfile"
}

HOOK_DIR=$(dirname "$(dirname "$(readlink -f "$0")")")

# Install OS-specific packages
case "$(uname -a 2>/dev/null)" in
  *GNU/Linux)
    if [ ! -z "$(command -v apt-get 2>/dev/null)" ]; then
      #echo "Found a Debian-based OS"
      __verify_or_source "${HOOK_DIR}/packages/apt"
    elif [ ! -z "$(command -v yum 2>/dev/null)" ]; then
      #echo "Found a RedHat-based OS"
      __verify_or_source "${HOOK_DIR}/packages/yum"
    else
      cat <<MSG >&2
${fg_red}Warning:${reset_color} your operating system is not recognized.
Unable to automatically install default packages required for these
configurations.
MSG
    fi
    ;;
  Darwin*)
    if [ ! -z "$(command -v brew 2>/dev/null)" ]; then
      #echo "Found MacOS with Homebrew installed"
      __verify_or_source "${HOOK_DIR}/packages/brew"
    else
      cat <<MSG >&2
${fg_red}Warning:${reset_color} you do not appear to have homebrew
installed and/or configured properly. Please install homebrew, if you
haven't already, and then run:
  ${fg_bold_white}brew doctor${reset_color}

Once finished with these steps, rerun ${fg_bold_white}rcup${reset_color}

MSG
    fi
    ;;
  *)
    cat <<MSG >&2
${fg_red}Warning:${reset_color} your operating system is not recognized.
Unable to automatically install default packages required for these
configurations.

MSG
    ;;
esac
