#!/bin/bash
set -e

HOOK_DIR="${0%/*}/../"

function __md5_generate() {
  local file=$1
  ( md5sum <"$file"; test $? = 127 && md5 <"$file" ) | cut -d' ' -f1
}
function __md5_verify() {
  local file=$1
  local checksumfile=${2:-"${file}.md5"}
  #echo "Verifying ${file} with ${checksumfile}"

  if [ $(__md5_generate "$file") = $(cat "$checksumfile") ]; then
    return 0
  else
    return 1
  fi
}
function __verify_or_source() {
  local file="$1"
  local checksumfile="${file}.md5"

  if [ -f "$checksumfile" ] && __md5_verify "$file" "$checksumfile"; then
    return 0
  fi

  source "$file"

  __md5_generate "$file" > "$checksumfile"
}

if command -v gem > /dev/null; then
  # TODO: Additional rubygems configurations?

  [ -f "${HOOK_DIR}/packages/rubygems" ] && \
    __verify_or_source "${HOOK_DIR}/packages/rubygems" \
    || true
fi
