#!/bin/bash
set -e

cat <<MSG
--------------------
>>  Python package manager (pip)
--------------------
MSG

function __md5_generate() {
  local file=$1
  openssl md5 "$file" | sed -e 's/MD5(.*)= //g'
}
function __md5_verify() {
  local file=$1
  local checksumfile=${2:-"${file}.md5"}

  if diff -q <(__md5_generate "$file") <(cat "$checksumfile") &>/dev/null; then
    return 0
  else
    return 1
  fi
}
function __verify_or_source() {
  local file="$1"
  local checksumfile="${file}.md5"

  if [ -f "$checksumfile" ] && __md5_verify "$file" "$checksumfile"; then
    return 0
  fi

  source "$file"

  __md5_generate "$file" > "$checksumfile"
}

HOOK_DIR="${0%/*}/../"

if [ -f "${HOOK_DIR}/packages/pip" ]; then
  __verify_or_source "${HOOK_DIR}/packages/pip"
fi

cat <<MSG
--------------------
>>  Done.
--------------------
MSG
