#!/usr/bin/env bash
set -euo pipefail

printf '%s\n' '-------------------------------------------------------'
printf '>>  %s\n' 'Symlinking Dotfiles'
printf '%s\n' '-------------------------------------------------------'
