#!/bin/sh

# Run git-guilt
if git rev-parse --quiet --verify HEAD~1; then
  git guilt HEAD~1
fi

if [ -f .git/hooks/post-commit.local ]; then
  # shellcheck disable=SC1091
  . .git/hooks/post-commit.local
fi

#.git/hooks/ctags >/dev/null 2>&1 &
