#!/bin/sh

if git rev-parse --quiet --verify HEAD~1 && command -v git-guilt 1>/dev/null 2>/dev/null; then
  # Run git-guilt
  git guilt HEAD~1 HEAD
fi

if [ -f .git/hooks/post-commit.local ]; then
  # shellcheck disable=SC1091
  . .git/hooks/post-commit.local
fi

#.git/hooks/ctags >/dev/null 2>&1 &
