#!/usr/bin/env bash

rm-pyc() {
  local dir
  if [ $# -eq 0 ]; then
    dir="."
    find "$dir" -iname '*.pyc' -exec rm {} \;
    find "$dir" -name '__pycache__' -type d -exec rm -r {} \; 2>&1 | sed -e '/^.* No such file or directory/d'
  else
    for dir in "$@"; do
      find "$dir" -iname '*.pyc' -exec rm {} \;
      find "$dir" -name '__pycache__' -type d -exec rm -r {} \; 2>&1 | sed -e '/^.* No such file or directory/d'
    done
  fi
}
