#!/usr/bin/env bash

symlink() {
  local source_file link_file usage
  usage="symlink [template-file] [target-destination]"

  if [ $# -lt 2 ]; then
    printf 'Usage: %s\n' "$usage" 1>&2
    return 1
  fi
  source_file="$1"; shift
  link_file="$1"; shift

  ln -s "$source_file" "$link_file"
}
