#!/usr/bin/env bash

unsymlink() {
  local source_file link_file usage
  usage="unsymlink [path-to-symlink]"

  if ! [ $# -gt 0 ]; then
    printf 'Usage: %s\n' "$usage" 1>&2
    return 1
  fi
  link_file="$1"; shift

  if [ ! -L "$link_file" ] && [ ! -e "$link_file" ]; then
    printf 'ERROR: %s\n' 'Target does not exist' 1>&2
    printf 'Usage: %s\n' "$usage" 1>&2
    return 1
  elif [ ! -L "$link_file" ] && [ -e "$link_file" ]; then
    printf 'ERROR: %s\n' 'Target is not a symlink' 1>&2
    printf 'Usage: %s\n' "$usage" 1>&2
    return 1
  elif [ -L "$link_file" ] && [ ! -e "$link_file" ]; then
    printf 'ERROR: %s\n' 'Symlink is broken' 1>&2
    printf 'Usage: %s\n' "$usage" 1>&2
    return 1
  fi
  source_file=$(readlink "$link_file")

  rm -f "$link_file"  # Removes the symlink, not the directory contents
  cp -r "$source_file" "$link_file"  # allows symlinking entire directories
}
