#!/bin/bash
set -e

__debug() {
  true &&
    __message "[DEBUG] >> ${*}" &&
    true
}

__plist_exists() {
  local plist_shortname plist usage
  usage=<<EOF
USAGE:  __plist_exists <plist>
EOF

  if [ ! $# -gt 0 ]; then
    printf '%s\n' "$usage" &>/dev/null
    return 1
  fi

  plist_shortname="$1"; shift
  plist="${HOME}/Library/Preferences/$plist_shortname"

  if [ -e "$plist" ]; then
    if __plist_exec "$plist" 'Print :' &>/dev/null; then
      # Exists and is queriable
      return 0
    fi
  fi

  return 1
}

__plist_exec() {
  local plist plb query usage
  plb='/usr/libexec/PlistBuddy'
  usage=<<EOF
USAGE:   __plist_exec <plist> <query>
EOF

  if [ ! $# -gt 1 ]; then
    printf '%s\n' "$usage" 1>&2
    return 1
  fi

  plist="${HOME}/Library/Preferences/$1"; shift
  query="$1"; shift

  if [ ! -e "$plist" ]; then
    printf 'No plist file found at %s\n' "$plist" 1>&2
    return 1
  fi

  "$plb" -c "$query" "$plist"
}

__plist_ensure_value() {
  local plist attr_tree desired_value value_datatype usage
  usage=<<EOF
USAGE:   __plist_ensure_value <plist> <attr-tree> <desired-value> <value-datatype>
EOF

  if [ ! $# -gt 3 ]; then
    printf '%s\n' "$usage" 1>&2
    return 1
  fi

  plist="$1"; shift
  attr_tree="$1"; shift
  desired_value="$1"; shift
  value_datatype="$1"; shift

  if ! (__plist_exec "$plist" "Print ${attr_tree}" &>/dev/null); then
    # Needs to be created
    __plist_exec "$plist" "Add ${attr_tree} ${value_datatype} ${desired_value}" &>/dev/null
  elif ! (__plist_exec "$plist" "Print ${attr_tree}" | grep -qFe "$desired_value"); then
    case "$value_datatype" in
      'dict'|'array')
        # skip
        ;;
      *)
        __plist_exec "$plist" "Set ${attr_tree} '${desired_value}'" &>/dev/null
        ;;
    esac
    # Needs to be changed
  else
    __debug "PList: '${attr_tree}' already exists as type '${value_datatype}' with value '${desired_value}'"
  fi
}

__message() {
  local msg
  msg=$1; shift

  printf '>>  %s\n' "$msg"
}

__post_message() {
  __message "$@" >> /tmp/dotfiles-install-messages
}


cat <<MSG
--------------------
>>  MacOS Customizations
--------------------
MSG

iterm2_plist='com.googlecode.iterm2.plist'
if __plist_exec "$iterm2_plist" 'Print :' &>/dev/null; then
  # Plist file actually exists and is readable!

  if ! (__plist_exec "$iterm2_plist" 'Print :GlobalKeyMap' 2>/dev/null | grep -qF '\[104;5u' &>/dev/null); then
    __message 'iTerm: Fix bug where <C-H> is interpreted as <BS>'

    # Ensure parents already exist
    __plist_ensure_value "$iterm2_plist" ':GlobalKeyMap' '{}' 'dict'
    __plist_ensure_value "$iterm2_plist" ':GlobalKeyMap:"0x68-0x40000"' '{}' 'dict'

    # Set values for keymap
    __plist_ensure_value "$iterm2_plist" ':GlobalKeyMap:"0x68-0x40000":Action' '10' 'integer'
    __plist_ensure_value "$iterm2_plist" ':GlobalKeyMap:"0x68-0x40000":Text' '"[104;5u"' 'string'
  fi

  __message 'iTerm: Quit when last window closes'
  __plist_ensure_value "$iterm2_plist" ':QuitWhenAllWindowsClosed' 'true' 'bool'

  # TODO: Detect if color scheme in current terminal session is 'solarized dark'
  # TODO: Automated fix of the iTerm2 color scheme for current profile
  __message 'iTerm2: Ensuring the default profile has the color preset for "Dark Background"'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks"' '[]' 'array'

  if ! __plist_exec "$iterm2_plist" 'Print :"New Bookmarks":0' &>/dev/null; then
    __message 'iTerm2: No default profile found. Creating one...'
    __plist_exec "$iterm2_plist" 'Add :"New Bookmarks": dict {}' &>/dev/null
    __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:Guid' '"37896A6A-111B-476A-9BE4-68EBF60F6D91"' 'string'
  fi

  # Scaffolding
  __message 'iTerm2: Configuring default profile with desired settings'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Ambiguous Double Width"' 'false' 'bool'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"BM Growl"' 'true' 'bool'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Blinking Cursor"' 'false' 'bool'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:Blur' 'false' 'bool'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Character Encoding"' '4' 'integer'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Close Sessions On End"' 'true' 'bool'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:Columns' '80' 'integer'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:Command' '""' 'string'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Custom Command"' '"No"' 'string'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Custom Directory"' '"No"' 'string'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Default Bookmark"' '"No"' 'string'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:Description' '"Default"' 'string'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Disable Window Sizing"' 'false' 'bool'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Flashing Bell"' 'true' 'bool'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Horizontal Spacing"' '1' 'real'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Idle Code"' '0' 'integer'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Mouse Reporting"' 'true' 'bool'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:Name' '"Default"' 'string'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Non Ascii Font"' '"Monaco 12"' 'string'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Non-ASCII Anti Aliased"' 'true' 'bool'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Normal Font"' '"Monaco 12"' 'string'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Option Key Sends"' '1' 'integer'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Prompt Before Closing 2"' 'false' 'bool'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Right Option Key Sends"' '0' 'integer'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:Rows' '25' 'integer'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:Screen' '-1' 'integer'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Scrollback Lines"' '1000' 'integer'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Send Code When Idle"' 'false' 'bool'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:Shortcut' '""' 'string'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Silence Bell"' 'false' 'bool'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Sync Title"' 'false' 'bool'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:Transparency' '0.0' 'real'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Unlimited Scrollback"' 'false' 'bool'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Use Non-ASCII Font"' 'false' 'bool'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Vertical Spacing"' '1' 'real'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Visual Bell"' 'false' 'bool'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Window Type"' '0' 'integer'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Working Directory"' "\"${HOME}\"" 'string'

  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Jobs To Ignore"' '[]' 'array'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Jobs To Ignore":0' '"rlogin"' 'string'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Jobs To Ignore":1' '"ssh"' 'string'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Jobs To Ignore":2' '"slogin"' 'string'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Jobs To Ignore":3' '"telnet"' 'string'

  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Semantic History"' '{}' 'dict'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Semantic History":action' '"best editor"' 'string'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Semantic History":editor' '"com.sublimetext.3"' 'string'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Semantic History":text' '""' 'string'

  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:Tags' '[]' 'array'

  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Badge Color"' '{}' 'dict'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Badge Color":"Alpha Component"' '0.5' 'real'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Badge Color":"Color Space"' '"Calibrated"' 'string'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Badge Color":"Blue Component"' '0.0' 'real'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Badge Color":"Green Component"' '0.0' 'real'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Badge Color":"Red Component"' '1' 'real'

  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map"' '{}' 'dict'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0x2d-0x40000"' '{}' 'dict'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0x2d-0x40000":Action' '11' 'integer'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0x2d-0x40000":Text' '"0x1f"' 'string'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0x32-0x40000"' '{}' 'dict'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0x32-0x40000":Action' '11' 'integer'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0x32-0x40000":Text' '"0x00"' 'string'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0x33-0x40000"' '{}' 'dict'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0x33-0x40000":Action' '11' 'integer'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0x33-0x40000":Text' '"0x1b"' 'string'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0x34-0x40000"' '{}' 'dict'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0x34-0x40000":Action' '11' 'integer'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0x34-0x40000":Text' '"0x1c"' 'string'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0x35-0x40000"' '{}' 'dict'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0x35-0x40000":Action' '11' 'integer'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0x35-0x40000":Text' '"0x1d"' 'string'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0x36-0x40000"' '{}' 'dict'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0x36-0x40000":Action' '11' 'integer'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0x36-0x40000":Text' '"0x1e"' 'string'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0x37-0x40000"' '{}' 'dict'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0x37-0x40000":Action' '11' 'integer'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0x37-0x40000":Text' '"0x1f"' 'string'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0x38-0x40000"' '{}' 'dict'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0x38-0x40000":Action' '11' 'integer'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0x38-0x40000":Text' '"0x7f"' 'string'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf700-0x220000"' '{}' 'dict'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf700-0x220000":Action' '10' 'integer'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf700-0x220000":Text' '"[1;2A"' 'string'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf700-0x240000"' '{}' 'dict'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf700-0x240000":Action' '10' 'integer'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf700-0x240000":Text' '"[1;5A"' 'string'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf700-0x260000"' '{}' 'dict'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf700-0x260000":Action' '10' 'integer'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf700-0x260000":Text' '"[1;6A"' 'string'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf701-0x220000"' '{}' 'dict'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf701-0x220000":Action' '10' 'integer'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf701-0x220000":Text' '"[1;2B"' 'string'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf701-0x240000"' '{}' 'dict'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf701-0x240000":Action' '10' 'integer'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf701-0x240000":Text' '"[1;5B"' 'string'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf701-0x260000"' '{}' 'dict'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf701-0x260000":Action' '10' 'integer'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf701-0x260000":Text' '"[1;6B"' 'string'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf702-0x220000"' '{}' 'dict'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf702-0x220000":Action' '10' 'integer'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf702-0x220000":Text' '"[1;2D"' 'string'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf702-0x240000"' '{}' 'dict'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf702-0x240000":Action' '10' 'integer'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf702-0x240000":Text' '"[1;5D"' 'string'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf702-0x260000"' '{}' 'dict'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf702-0x260000":Action' '10' 'integer'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf702-0x260000":Text' '"[1;6D"' 'string'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf703-0x220000"' '{}' 'dict'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf703-0x220000":Action' '10' 'integer'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf703-0x220000":Text' '"[1;2C"' 'string'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf703-0x240000"' '{}' 'dict'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf703-0x240000":Action' '10' 'integer'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf703-0x240000":Text' '"[1;5C"' 'string'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf703-0x260000"' '{}' 'dict'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf703-0x260000":Action' '10' 'integer'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf703-0x260000":Text' '"[1;6C"' 'string'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf704-0x200000"' '{}' 'dict'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf704-0x200000":Action' '10' 'integer'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf704-0x200000":Text' '"[1;2P"' 'string'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf705-0x200000"' '{}' 'dict'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf705-0x200000":Action' '10' 'integer'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf705-0x200000":Text' '"[1;2Q"' 'string'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf706-0x200000"' '{}' 'dict'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf706-0x200000":Action' '10' 'integer'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf706-0x200000":Text' '"[1;2R"' 'string'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf707-0x200000"' '{}' 'dict'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf707-0x200000":Action' '10' 'integer'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf707-0x200000":Text' '"[1;2S"' 'string'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf708-0x200000"' '{}' 'dict'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf708-0x200000":Action' '10' 'integer'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf708-0x200000":Text' '"[15;2~"' 'string'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf709-0x200000"' '{}' 'dict'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf709-0x200000":Action' '10' 'integer'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf709-0x200000":Text' '"[17;2~"' 'string'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf70a-0x200000"' '{}' 'dict'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf70a-0x200000":Action' '10' 'integer'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf70a-0x200000":Text' '"[18;2~"' 'string'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf70b-0x200000"' '{}' 'dict'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf70b-0x200000":Action' '10' 'integer'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf70b-0x200000":Text' '"[19;2~"' 'string'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf70c-0x200000"' '{}' 'dict'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf70c-0x200000":Action' '10' 'integer'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf70c-0x200000":Text' '"[20;2~"' 'string'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf70d-0x200000"' '{}' 'dict'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf70d-0x200000":Action' '10' 'integer'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf70d-0x200000":Text' '"[21;2~"' 'string'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf70e-0x200000"' '{}' 'dict'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf70e-0x200000":Action' '10' 'integer'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf70e-0x200000":Text' '"[23;2~"' 'string'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf70f-0x200000"' '{}' 'dict'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf70f-0x200000":Action' '10' 'integer'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf70f-0x200000":Text' '"[24;2~"' 'string'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf729-0x200000"' '{}' 'dict'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf729-0x200000":Action' '10' 'integer'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf729-0x200000":Text' '"[1;2H"' 'string'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf729-0x400000"' '{}' 'dict'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf729-0x400000":Action' '10' 'integer'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf729-0x400000":Text' '"[1;5H"' 'string'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf72b-0x200000"' '{}' 'dict'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf72b-0x200000":Action' '10' 'integer'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf72b-0x200000":Text' '"[1;2F"' 'string'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf72b-0x400000"' '{}' 'dict'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf72b-0x400000":Action' '10' 'integer'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Keyboard Map":"0xf72b-0x400000":Text' '"[1;5F"' 'string'

  __message 'iTerm2: Configuring default profile with optimum coloring'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"ASCII Anti Aliased"' 'true' 'bool'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Terminal Type"' '"xterm-256color"' 'string'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Use Bold Font"' 'true' 'bool'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Use Bright Bold"' 'true' 'bool'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Use Italic Font"' 'true' 'bool'

  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Ansi 0 Color"' '{}' 'dict'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Ansi 0 Color":"Blue Component"' '0.0' 'real'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Ansi 0 Color":"Green Component"' '0.0' 'real'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Ansi 0 Color":"Red Component"' '0.0' 'real'

  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Ansi 1 Color"' '{}' 'dict'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Ansi 1 Color":"Blue Component"' '0.0' 'real'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Ansi 1 Color":"Green Component"' '0.0' 'real'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Ansi 1 Color":"Red Component"' '0.73333334922790527' 'real'

  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Ansi 2 Color"' '{}' 'dict'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Ansi 2 Color":"Blue Component"' '0.0' 'real'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Ansi 2 Color":"Green Component"' '0.73333334922790527' 'real'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Ansi 2 Color":"Red Component"' '0.0' 'real'

  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Ansi 3 Color"' '{}' 'dict'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Ansi 3 Color":"Blue Component"' '0.0' 'real'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Ansi 3 Color":"Green Component"' '0.73333334922790527' 'real'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Ansi 3 Color":"Red Component"' '0.73333334922790527' 'real'

  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Ansi 4 Color"' '{}' 'dict'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Ansi 4 Color":"Blue Component"' '0.73333334922790527' 'real'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Ansi 4 Color":"Green Component"' '0.0' 'real'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Ansi 4 Color":"Red Component"' '0.0' 'real'

  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Ansi 5 Color"' '{}' 'dict'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Ansi 5 Color":"Blue Component"' '0.73333334922790527' 'real'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Ansi 5 Color":"Green Component"' '0.0' 'real'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Ansi 5 Color":"Red Component"' '0.73333334922790527' 'real'

  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Ansi 6 Color"' '{}' 'dict'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Ansi 6 Color":"Blue Component"' '0.73333334922790527' 'real'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Ansi 6 Color":"Green Component"' '0.73333334922790527' 'real'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Ansi 6 Color":"Red Component"' '0.0' 'real'

  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Ansi 7 Color"' '{}' 'dict'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Ansi 7 Color":"Blue Component"' '0.73333334922790527' 'real'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Ansi 7 Color":"Green Component"' '0.73333334922790527' 'real'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Ansi 7 Color":"Red Component"' '0.73333334922790527' 'real'

  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Ansi 8 Color"' '{}' 'dict'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Ansi 8 Color":"Blue Component"' '0.3333333432674408' 'real'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Ansi 8 Color":"Green Component"' '0.3333333432674408' 'real'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Ansi 8 Color":"Red Component"' '0.3333333432674408' 'real'

  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Ansi 9 Color"' '{}' 'dict'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Ansi 9 Color":"Blue Component"' '0.3333333432674408' 'real'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Ansi 9 Color":"Green Component"' '0.3333333432674408' 'real'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Ansi 9 Color":"Red Component"' '1' 'real'

  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Ansi 10 Color"' '{}' 'dict'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Ansi 10 Color":"Blue Component"' '0.3333333432674408' 'real'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Ansi 10 Color":"Green Component"' '1' 'real'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Ansi 10 Color":"Red Component"' '0.3333333432674408' 'real'

  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Ansi 11 Color"' '{}' 'dict'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Ansi 11 Color":"Blue Component"' '0.3333333432674408' 'real'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Ansi 11 Color":"Green Component"' '1' 'real'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Ansi 11 Color":"Red Component"' '1' 'real'

  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Ansi 12 Color"' '{}' 'dict'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Ansi 12 Color":"Blue Component"' '1' 'real'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Ansi 12 Color":"Green Component"' '0.3333333432674408' 'real'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Ansi 12 Color":"Red Component"' '0.3333333432674408' 'real'

  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Ansi 13 Color"' '{}' 'dict'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Ansi 13 Color":"Blue Component"' '1' 'real'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Ansi 13 Color":"Green Component"' '0.3333333432674408' 'real'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Ansi 13 Color":"Red Component"' '1' 'real'

  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Ansi 14 Color"' '{}' 'dict'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Ansi 14 Color":"Blue Component"' '1' 'real'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Ansi 14 Color":"Green Component"' '1' 'real'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Ansi 14 Color":"Red Component"' '0.3333333432674408' 'real'

  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Ansi 15 Color"' '{}' 'dict'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Ansi 15 Color":"Blue Component"' '1' 'real'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Ansi 15 Color":"Green Component"' '1' 'real'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Ansi 15 Color":"Red Component"' '1' 'real'

  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Background Color"' '{}' 'dict'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Background Color":"Blue Component"' '0.0' 'real'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Background Color":"Green Component"' '0.0' 'real'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Background Color":"Red Component"' '0.0' 'real'

  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Bold Color"' '{}' 'dict'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Bold Color":"Blue Component"' '1' 'real'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Bold Color":"Green Component"' '1' 'real'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Bold Color":"Red Component"' '1' 'real'

  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Cursor Color"' '{}' 'dict'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Cursor Color":"Blue Component"' '0.73333334922790527' 'real'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Cursor Color":"Green Component"' '0.73333334922790527' 'real'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Cursor Color":"Red Component"' '0.73333334922790527' 'real'

  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Foreground Color"' '{}' 'dict'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Foreground Color":"Blue Component"' '0.73333334922790527' 'real'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Foreground Color":"Green Component"' '0.73333334922790527' 'real'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Foreground Color":"Red Component"' '0.73333334922790527' 'real'

  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Selection Color"' '{}' 'dict'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Selection Color":"Blue Component"' '1' 'real'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Selection Color":"Green Component"' '0.8353000283241272' 'real'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Selection Color":"Red Component"' '0.70980000495910645' 'real'

  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Cursor Guide Color"' '{}' 'dict'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Cursor Guide Color":"Alpha Component"' '0.25' 'real'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Cursor Guide Color":"Color Space"' '"Calibrated"' 'string'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Cursor Guide Color":"Blue Component"' '1' 'real'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Cursor Guide Color":"Green Component"' '0.91000000000000003' 'real'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Cursor Guide Color":"Red Component"' '0.65000000000000002' 'real'

  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Cursor Text Color"' '{}' 'dict'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Cursor Text Color":"Blue Component"' '1' 'real'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Cursor Text Color":"Green Component"' '1' 'real'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Cursor Text Color":"Red Component"' '1' 'real'

  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Link Color"' '{}' 'dict'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Link Color":"Alpha Component"' '1' 'real'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Link Color":"Color Space"' '"Calibrated"' 'string'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Link Color":"Blue Component"' '0.67800000000000005' 'real'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Link Color":"Green Component"' '0.27000000000000002' 'real'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Link Color":"Red Component"' '0.023' 'real'

  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Selected Text Color"' '{}' 'dict'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Selected Text Color":"Blue Component"' '0.0' 'real'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Selected Text Color":"Green Component"' '0.0' 'real'
  __plist_ensure_value "$iterm2_plist" ':"New Bookmarks":0:"Selected Text Color":"Red Component"' '0.0' 'real'


  default_profile_guid=$(__plist_exec "$iterm2_plist" 'Print :"New Bookmarks":0:Guid' 2>/dev/null)
  if [ -n "$default_profile_guid" ]; then
    __plist_ensure_value "$iterm2_plist" ':"Default Bookmark Guid"' "\"${default_profile_guid}\"" 'string'
  fi
fi

globalprefs_plist='.GlobalPreferences.plist'
if __plist_exec "$globalprefs_plist" 'Print :' &>/dev/null; then
  __message 'Keyboard: MacOS observes readline key bindings in the terminal'
  __plist_ensure_value "$globalprefs_plist" ':AppleKeyboardUIMode' '2' 'integer'
fi

cat <<MSG
--------------------
>>  Done.
--------------------
MSG
