#!/usr/bin/env bash
set -euo pipefail

if ! uname -a 2>/dev/null | grep -qe '.*GNU/Linux' &>/dev/null; then
  # Must not be a linux variant
  exit 0
fi
if ! command -v 'apt-get' &>/dev/null; then
  # Must not be Ubuntu variant
  exit 0
fi
HOOK_DIR=$(realpath -- "${0%/*}/../")

__message() {
  printf '>>  %s\n' "$*"
}
__error() {
  __message "$*" >&2
}
__fatal() {
  __error "$*"
  exit 1
}


if [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
  printf '%s\n' '-------------------------------------------------------'
  __message 'Ubuntu Customizations'
  printf '%s\n' '-------------------------------------------------------'

  if ! command -v dconf &>/dev/null; then
    __fatal "Missing \`dconf' command"
  fi
  friendly_hook_dir=$(printf '%s' "${HOOK_DIR/$HOME/~}" | sed -e 's!'"${HOME}"'!~!g')

  if [ -f "${HOOK_DIR}/gnome_terminal_settings.txt" ]; then
    dconf reset -f /org/gnome/terminal/
    dconf load /org/gnome/terminal/ <"${HOOK_DIR}/gnome_terminal_settings.txt"
    __message "GNOME Terminal settings have been reset to the preferred state in '${friendly_hook_dir}/gnome_terminal_settings.txt'"
  else
    __fatal "Expected '${friendly_hook_dir}/gnome_terminal_settings.txt' to exist, but it does not"
  fi
fi
