#!/usr/bin/env bash
set -euo pipefail

HOOK_DIR="${0%/*}/../"

__message() {
  local msg
  msg=$1; shift

  printf '>>  %s\n' "$msg"
}

__md5_generate() {
  local file=$1
  openssl md5 "$file" | sed -e 's/MD5(.*)= //g'
}
__md5_verify() {
  local file=$1
  local checksumfile=${2:-"${file}.md5"}
  #echo "Verifying ${file} with ${checksumfile}"

  if diff -q <(__md5_generate "$file") <(cat "$checksumfile") &>/dev/null; then
    return 0
  else
    return 1
  fi
}
__verify_or_source() {
  local file="$1"
  local checksumfile="${file}.md5"

  if [ -f "$checksumfile" ] && __md5_verify "$file" "$checksumfile"; then
    return 0
  fi

  source "$file"

  __md5_generate "$file" > "$checksumfile"
}

__install_packages() {
  local package_file
  package_file="${HOOK_DIR}/packages/$1"; shift

  if [ -f "${package_file}" ]; then
    __verify_or_source "${package_file}"
  fi
}


if [[ "${BASH_SOURCE[0]}" = "$0" ]] && command -v apm &>/dev/null; then
  printf '%s\n' '-------------------------------------------------------'
  __message 'Atom package manager (apm)'
  printf '%s\n' '-------------------------------------------------------'

  __install_packages 'apm'
fi
