#!/usr/bin/env bash
set -euo pipefail

HOOK_DIR="${0%/*}/../"
source "${HOOK_DIR}/lib/base.sh"
trap -- '__cleanup_temp' EXIT

__grab_kubectl_version() {
  local GOOS GOARCH tmp_dir binary version
  binary="$1"
  tmp_dir="$(mktemp-dir)"

  if [ -n "${2:-}" ]; then
    version="$2"
  else
    version="$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)"
  fi
  if [ -x "${HOME}/.bin/${binary}" ] && ("${HOME}/.bin/${binary}" version 2>/dev/null || true) | grep -qFe "${version}" &>/dev/null; then
    __message 'kubectl is up-to-date'
    return 0
  fi
  __message "Downloading kubectl (${version})"

  GOOS="$(get-goos)"
  GOARCH="$(get-goarch)"

  pushd "${tmp_dir}" &>/dev/null
  curl -SLo ./kubectl "https://storage.googleapis.com/kubernetes-release/release/${version}/bin/${GOOS}/${GOARCH}/kubectl"
  chmod +x ./kubectl
  mv ./kubectl "${HOME}/.bin/${binary}"
  popd &>/dev/null
}

__install_kubectx() {
  set-git-repo "${HOME}/.kubectx" 'https://github.com/ahmetb/kubectx.git' 'kubectx'

  mkdir -p "${HOME}/.local/bin"
  command ln -fs "${HOME}/.kubectx/kubectx" "${HOME}/.local/bin/kubectx"
  command ln -fs "${HOME}/.kubectx/kubens" "${HOME}/.local/bin/kubens"
  command ln -fs "${HOME}/.kubectx/completion/kubectx.zsh" "${HOME}/.zsh/completion/_kubectx"
  command ln -fs "${HOME}/.kubectx/completion/kubens.zsh" "${HOME}/.zsh/completion/_kubens"
}

__grab_helm_version() {
  local GOOS GOARCH tmp_dir binary version
  binary="$1"
  version="$2"

  if [ -x "${HOME}/.bin/${binary}" ]; then
    return 0
  fi

  GOOS="$(get-goos)"
  GOARCH="$(get-goarch)"
  tmp_dir="$(mktemp-dir)"

  pushd "${tmp_dir}" &>/dev/null
  curl -SLo ./helm.tar.gz "https://get.helm.sh/helm-v${version}-${GOOS}-${GOARCH}.tar.gz"
  tar xzf ./helm.tar.gz --strip-components=1
  chmod +x ./helm
  mv ./helm "${HOME}/.bin/${binary}"
  popd &>/dev/null
}

if [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
  printf '%s\n' '-------------------------------------------------------'
  __message 'Kubernetes Tools'
  printf '%s\n' '-------------------------------------------------------'

  mkdir -p "${HOME}/.bin"
  __grab_kubectl_version 'kubectl'

  __install_kubectx

  __message 'Downloading Helm 2.16.1'
  __grab_helm_version 'helm2' '2.16.1'
  __message 'Downloading Helm 3.0.2'
  __grab_helm_version 'helm3' '3.0.2'
  __message 'Setting Helm 3 to be the default Helm'
  command ln -fs "${HOME}/.bin/helm3" "${HOME}/.bin/helm"
fi
