#!/usr/bin/env bash
set -euo pipefail

__message() {
  local msg
  msg=$1; shift

  printf '>>  %s\n' "$msg"
}

__error() {
  __message "$*" >&2
}

__fatal() {
  __error "$*"
  exit 1
}

__md5_generate() {
  local file=$1
  openssl md5 "$file" | sed -e 's/MD5(.*)= //g'
}
__md5_verify() {
  local file=$1
  local checksumfile=${2:-"${file}.md5"}
  #echo "Verifying ${file} with ${checksumfile}"

  if diff -q <(__md5_generate "$file") <(cat "$checksumfile") &>/dev/null; then
    return 0
  else
    return 1
  fi
}
__verify_base_and_local_md5() {
  __md5_verify "$1" && ([ ! -e "$1".local ] || __md5_verify "$1".local)
}
__generate_base_and_local_md5() {
  if [ -e "$1" ]; then
    __md5_generate "$1" > "$1".md5
  fi
  if [ -e "$1".local ]; then
    __md5_generate "$1".local > "$1".local.md5
  fi
}

__ensure_plugin_manager() {
  if [ ! -e "$HOME"/.config/nvim/autoload/plug.vim ]; then
    printf '>>  NeoVim plugin manager is being installed... '
    command curl -fLo "$HOME"/.config/nvim/autoload/plug.vim --create-dirs \
      https://github.com/junegunn/vim-plug/raw/master/plug.vim
    printf 'Done.\n'
  fi
}

__install_plugins() {
  local nvim_bundle_config
  nvim_bundle_config="${HOME}/.config/nvim/bundles.vim"

  if [ ! -e "${nvim_bundle_config}" ]; then
    return 0
  fi

  printf '>>  NeoVim bundles are being installed... '
  if printf 'PlugInstall|qall\n' | command nvim -u "${nvim_bundle_config}" -es; then
    printf 'Done\n'
  else
    printf 'ERROR\n'
    __error "Encountered an error when running \`nvim +PlugInstall\`"
  fi
}

__update_plugins() {
  local nvim_bundle_config
  nvim_bundle_config="${HOME}/.config/nvim/bundles.vim"

  if [ ! -e "${nvim_bundle_config}" ]; then
    return 0
  fi

  printf '>>  NeoVim bundles are being updated... '
  if command nvim -u "${nvim_bundle_config}" -c 'PlugUpdate' -c qall; then
    printf 'Done\n'
  else
    printf 'ERROR\n'
    __error "Encountered an error when updating vim plugins"
  fi
}

__update_docs() {
  printf '>>  NeoVim plugin help docs are being updated... '
  if [ ! -e "${HOME}/.config/nvim/doc/plug.txt" ]; then
    command curl -fLo "${HOME}/.config/nvim/doc/plug.txt" --create-dirs \
      https://github.com/junegunn/vim-plug/raw/master/doc/plug.txt 1>/dev/null 2>/dev/null
  fi
  # shellcheck disable=SC2016
  printf 'helptags $HOME/.config/nvim/doc\nqall\n' | command nvim -u "${HOME}/.config/nvim/init.vim" -es
  printf 'Done.\n'
}

if [[ "${BASH_SOURCE[0]}" = "$0" ]] && command -v nvim 1>/dev/null 2>/dev/null; then
  printf '%s\n' '-------------------------------------------------------'
  __message 'NeoVim plugins'
  printf '%s\n' '-------------------------------------------------------'

  pushd "${HOME}" 1>/dev/null 2>/dev/null
  __ensure_plugin_manager
  __install_plugins
  __update_plugins
  __update_docs
  popd 1>/dev/null 2>/dev/null
fi
