#!/usr/bin/env bash
set -euo pipefail

__message() {
  local msg
  msg=$1; shift

  printf '>>  %s\n' "$msg"
}

__error() {
  __message "$*" >&2
}

__fatal() {
  __error "$*"
  exit 1
}

__md5_generate() {
  local file=$1
  openssl md5 "$file" | sed -e 's/MD5(.*)= //g'
}
__md5_verify() {
  local file=$1
  local checksumfile=${2:-"${file}.md5"}
  #echo "Verifying ${file} with ${checksumfile}"

  if diff -q <(__md5_generate "$file") <(cat "$checksumfile") &>/dev/null; then
    return 0
  else
    return 1
  fi
}
__verify_base_and_local_md5() {
  __md5_verify "$1" && ([ ! -e "$1".local ] || __md5_verify "$1".local)
}
__generate_base_and_local_md5() {
  if [ -e "$1" ]; then
    __md5_generate "$1" > "$1".md5
  fi
  if [ -e "$1".local ]; then
    __md5_generate "$1".local > "$1".local.md5
  fi
}

__ensure_plugin_manager() {
  if [ ! -e "$HOME"/.config/nvim/autoload/plug.vim ]; then
    curl -fLo "$HOME"/.config/nvim/autoload/plug.vim --create-dirs \
      https://github.com/junegunn/vim-plug/raw/master/plug.vim
  fi
}

__install_plugins() {
  local nvim_bundle_config
  nvim_bundle_config="${HOME}/.config/nvim/bundles.vim"

  if [ ! -e "${nvim_bundle_config}" ]; then
    return 0
  fi

  if ! __verify_base_and_local_md5 "${nvim_bundle_config}"; then
    printf '>>  NeoVim bundles are being installed... '
    if command nvim -u "${nvim_bundle_config}" +'PlugInstall' +'qall' </dev/null &>/dev/null; then
      printf 'Done\n'
      __generate_base_and_local_md5 "${nvim_bundle_config}"
    else
      printf 'ERROR\n'
      __error 'Encountered an error when running `nvim +PlugInstall`'
    fi
  fi
}

__update_plugins() {
  local nvim_bundle_config
  nvim_bundle_config="${HOME}/.config/nvim/bundles.vim"

  if [ ! -e "${nvim_bundle_config}" ]; then
    return 0
  fi

  printf '>>  NeoVim bundles are being updated... '
  if command nvim -u "${nvim_bundle_config}" +'PlugUpdate' +'qall' </dev/null &>/dev/null; then
    printf 'Done\n'
  else
    printf 'ERROR\n'
    __error 'Encountered an error when running `nvim +PlugUpdate`'
  fi
}

if [[ "${BASH_SOURCE[0]}" = "$0" ]] && command -v nvim &>/dev/null; then
  printf '%s\n' '-------------------------------------------------------'
  __message 'NeoVim plugins'
  printf '%s\n' '-------------------------------------------------------'

  __ensure_plugin_manager
  __install_plugins
  __update_plugins
fi
