#!/usr/bin/env bash
set -euo pipefail

HOOK_DIR="${0%/*}/../"
source "${HOOK_DIR}/lib/base.sh"
trap -- '__cleanup_temp' EXIT

__grab_terraform_version() {
  local GOOS GOARCH tmp_dir binary version url
  version="$1"

  if [ -x "${HOME}/.terraform-versions/v${version}/terraform" ]; then
    return 0
  fi

  GOOS="$(get-goos)"
  GOARCH="$(get-goarch)"
  if [ "$GOARCH" = 'arm64' ]; then
    GOARCH='arm'
  fi

  tmp_dir="$(mktemp-dir)"
  url="https://releases.hashicorp.com/terraform/${version}/terraform_${version}_${GOOS}_${GOARCH}.zip"

  mkdir -p "${HOME}/.terraform-versions/v${version}"
  pushd "${tmp_dir}" &>/dev/null
  curl -SsLo ./terraform.zip "$url"
  unzip -d "${HOME}/.terraform-versions/v${version}" ./terraform.zip
  chmod +x "${HOME}/.terraform-versions/v${version}/terraform"
  popd &>/dev/null
}

if [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
  printf '%s\n' '-------------------------------------------------------'
  __message 'Terraform'
  printf '%s\n' '-------------------------------------------------------'

  mkdir -p "${HOME}/.bin"
  __message 'Downloading Terraform v0.11.14'
  __grab_terraform_version '0.11.14'
  __message 'Downloading Terraform v0.12.24'
  __grab_terraform_version '0.12.24'
  __message 'Setting Terraform 12 to be the default Terraform'
  command ln -fs "${HOME}/.terraform-versions/v0.12.24/terraform" "${HOME}/.bin/terraform"
fi
