#!/usr/bin/env bash
set -euo pipefail

HOOK_DIR="${0%/*}/../"
source "${HOOK_DIR}/lib/base.sh"
trap -- '__cleanup_temp' EXIT

__grab_terraform_version() {
  local GOOS GOARCH tmp_dir binary version url
  binary="$1"
  version="$2"

  if [ -x "${HOME}/.bin/${binary}" ]; then
    return 0
  fi

  GOOS="$(get-goos)"
  GOARCH="$(get-goarch)"
  if [ "$GOARCH" = 'arm64' ]; then
    GOARCH='arm'
  fi

  tmp_dir="$(mktemp-dir)"
  url="https://releases.hashicorp.com/terraform/${version}/terraform_${version}_${GOOS}_${GOARCH}.zip"

  pushd "${tmp_dir}" &>/dev/null
  curl -SsLo ./terraform.zip "$url"
  unzip ./terraform.zip
  chmod +x ./terraform
  mv ./terraform "${HOME}/.bin/${binary}"
  popd &>/dev/null
}

if [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
  printf '%s\n' '-------------------------------------------------------'
  __message 'Terraform'
  printf '%s\n' '-------------------------------------------------------'

  mkdir -p "${HOME}/.bin"
  __message 'Downloading Terraform v0.11.14'
  __grab_terraform_version 'terraform11' '0.11.14'
  __message 'Downloading Terraform v0.12.24'
  __grab_terraform_version 'terraform12' '0.12.24'
  __message 'Setting Terraform 12 to be the default Terraform'
  command ln -fs "${HOME}/.bin/terraform12" "${HOME}/.bin/terraform"
fi
