#!/usr/bin/env bash
set -euo pipefail

HOOK_DIR="${0%/*}/../"
source "${HOOK_DIR}/lib/base.sh"
trap -- '__cleanup_temp' EXIT


__install_testssl() {
  local version install_dir
  version="$1"
  install_dir="${2:-${HOME}/.testssl}"

  set-git-repo "$install_dir" 'https://github.com/drwetter/testssl.sh.git' 'testssl.sh' "$version"
  command ln -fvs "${install_dir}/testssl.sh" "${HOME}/.bin/test-ssl"
}


if [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
  printf '%s\n' '-------------------------------------------------------'
  __message 'TestSSL'
  printf '%s\n' '-------------------------------------------------------'

  __install_testssl '3.0rc6'
fi
