#!/usr/bin/env bash
set -euo pipefail

HOOK_DIR="${0%/*}/../"
source "${HOOK_DIR}/lib/base.sh"
trap -- '__cleanup_temp' EXIT

__grab_terraform_version() {
  local GOARCH tmp_dir binary version
  binary="$1"
  version="$2"

  if [ -x "${HOME}/.bin/${binary}" ]; then
    return 0
  fi

  if is_mac; then
    GOARCH="darwin_$(get-goarch)"
  else
    GOARCH="linux_$(get-goarch)"
  fi
  tmp_dir="$(mktemp-dir)"

  pushd "${tmp_dir}" &>/dev/null
  curl -SsLo ./terraform.zip "https://releases.hashicorp.com/terraform/${version}/terraform_${version}_${GOARCH}.zip"
  unzip ./terraform.zip
  chmod +x ./terraform
  mv ./terraform "${HOME}/.bin/${binary}"
  popd &>/dev/null
}

if [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
  printf '%s\n' '-------------------------------------------------------'
  __message 'Terraform'
  printf '%s\n' '-------------------------------------------------------'

  mkdir -p "${HOME}/.bin"
  __message 'Downloading Terraform v0.11.14'
  __grab_terraform_version 'terraform11' '0.11.14'
  __message 'Downloading Terraform v0.12.13'
  __grab_terraform_version 'terraform12' '0.12.13'
  __message 'Setting Terraform 12 to be the default Terraform'
  command ln -fs "${HOME}/.bin/terraform12" "${HOME}/.bin/terraform"
fi
