#!/usr/bin/env bash
set -euo pipefail

__message() {
  local msg
  msg=$1; shift

  printf '>>  %s\n' "$msg"
}

__error() {
  __message "$*" >&2
}

__fatal() {
  __error "$*"
  exit 1
}

__md5_generate() {
  local file=$1
  ( md5sum <"$file" 2>/dev/null ; test $? = 127 && md5 -r <"$file" ) | cut -d' ' -f1
}
__md5_verify() {
  local file=$1
  local checksumfile=${2:-"${file}.md5"}
  #echo "Verifying ${file} with ${checksumfile}"

  if [ ! -e "$file" ] || [ ! -e "$checksumfile" ]; then
    return 1
  fi

  if [ "$(__md5_generate "$file")" == "$(cat "$checksumfile")" ]; then
    return 0
  else
    return 1
  fi
}
__verify_base_and_local_md5() {
  __md5_verify "$1" && ([ ! -e "$1".local ] || __md5_verify "$1".local)
}
__generate_base_and_local_md5() {
  if [ -e "$1" ]; then
    __md5_generate "$1" > "$1".md5
  fi
  if [ -e "$1".local ]; then
    __md5_generate "$1".local > "$1".local.md5
  fi
}

__ensure_plugin_manager() {
  if [ ! -e "$HOME"/.vim/autoload/plug.vim ]; then
    curl -fLo "$HOME"/.vim/autoload/plug.vim --create-dirs \
      https://github.com/junegunn/vim-plug/raw/master/plug.vim
  fi
}

__install_plugins() {
  local vim_bundle_config
  vim_bundle_config="${HOME}/.vimrc.bundles"

  if [ ! -e "${vim_bundle_config}" ]; then
    return 0
  fi

  if ! __verify_base_and_local_md5 "${vim_bundle_config}"; then
    printf '>>  Vim plugins are being installed... '
    if command vim -u "${vim_bundle_config}" +'PlugInstall' +'qall' </dev/null &>/dev/null; then
      printf 'Done\n'
      __generate_base_and_local_md5 "${vim_bundle_config}"
    else
      printf 'ERROR\n'
      __error 'Encountered an error when running `vim +PlugInstall`'
    fi
  fi
}

__update_plugins() {
  local vim_bundle_config
  vim_bundle_config="${HOME}/.vimrc.bundles"

  if [ ! -e "${vim_bundle_config}" ]; then
    return 0
  fi

  printf '>>  Vim plugins are being updated... '
  if command vim -u "${vim_bundle_config}" +'PlugUpdate' +'qall' </dev/null &>/dev/null; then
    printf 'Done\n'
  else
    printf 'ERROR\n'
    __error 'Encountered an error when running `vim +PlugInstall`'
  fi
}


if [[ "${BASH_SOURCE[0]}" = "$0" ]] && command -v &>/dev/null; then
  printf '%s\n' '--------------------'
  __message 'Vim plugins'
  printf '%s\n' '--------------------'

  __ensure_plugin_manager
  __install_plugins
  __update_plugins

  printf '%s\n' '--------------------'
  __message 'Done'
  printf '%s\n' '--------------------'
fi
