#!/bin/bash
set -e

cat <<MSG
--------------------
>>  NeoVim plugins
--------------------
MSG

function __md5_generate() {
  local file=$1
  ( md5sum <"$file" 2>/dev/null ; test $? = 127 && md5 -r <"$file" ) | cut -d' ' -f1
}
function __md5_verify() {
  local file=$1
  local checksumfile=${2:-"${file}.md5"}
  #echo "Verifying ${file} with ${checksumfile}"

  if [ ! -e "$file" ] || [ ! -e "$checksumfile" ]; then
    return 1
  fi

  if [ "$(__md5_generate "$file")" == "$(cat "$checksumfile")" ]; then
    return 0
  else
    return 1
  fi
}
function __verify_base_and_local_md5() {
  __md5_verify "$1" && ([ ! -e "$1".local ] || __md5_verify "$1".local)
}
function __generate_base_and_local_md5() {
  if [ -e "$1" ]; then
    __md5_generate "$1" > "$1".md5
  fi
  if [ -e "$1".local ]; then
    __md5_generate "$1".local > "$1".local.md5
  fi
}

if [ ! -e "$HOME"/.config/nvim/autoload/plug.vim ]; then
  curl -fLo "$HOME"/.config/nvim/autoload/plug.vim --create-dirs \
    https://github.com/junegunn/vim-plug/raw/master/plug.vim
fi

if [ -e "$HOME"/.config/nvim/bundles.vim ]; then
  if __verify_base_and_local_md5 "$HOME"/.config/nvim/bundles.vim; then
    echo "NeoVim bundles are being updated..."
    command nvim -u "$HOME"/.config/nvim/bundles.vim +PlugUpdate +'PlugClean!' +qall </dev/null &>/dev/null
  else
    echo "NeoVim bundles are being updated..."
    command nvim -u "$HOME"/.config/nvim/bundles.vim +PlugInstall +PlugUpdate +'PlugClean!' +qall </dev/null &>/dev/null \
      && __generate_base_and_local_md5 "$HOME"/.config/nvim/bundles.vim \
      && echo "NeoVim bundles were updated" \
      || echo "ERROR: encountered an error when running \`nvim +'PlugInstall'\`" >&2
  fi
fi

cat <<MSG
--------------------
>>  Done.
--------------------
MSG
