#!/bin/bash
set -e

if ! command -v vim &>/dev/null; then
  # Vim is not installed, so we don't need to install the plugins
  exit 0
fi

cat <<MSG
--------------------
>>  Vim plugins
--------------------
MSG

function __md5_generate() {
  local file=$1
  ( md5sum <"$file" 2>/dev/null ; test $? = 127 && md5 -r <"$file" ) | cut -d' ' -f1
}
function __md5_verify() {
  local file=$1
  local checksumfile=${2:-"${file}.md5"}
  #echo "Verifying ${file} with ${checksumfile}"

  if [ ! -e "$file" ] || [ ! -e "$checksumfile" ]; then
    return 1
  fi

  if [ "$(__md5_generate "$file")" == "$(cat "$checksumfile")" ]; then
    return 0
  else
    return 1
  fi
}
function __verify_base_and_local_md5() {
  __md5_verify "$1" && ([ ! -e "$1".local ] || __md5_verify "$1".local)
}
function __generate_base_and_local_md5() {
  if [ -e "$1" ]; then
    __md5_generate "$1" > "$1".md5
  fi
  if [ -e "$1".local ]; then
    __md5_generate "$1".local > "$1".local.md5
  fi
}

# Install Vim-Plug and any plugins it handles
if [ ! -e "$HOME"/.vim/autoload/plug.vim ]; then
  curl -fLo "$HOME"/.vim/autoload/plug.vim --create-dirs \
      https://github.com/junegunn/vim-plug/raw/master/plug.vim
fi

if [ -e "$HOME"/.vimrc.bundles ]; then
  if ! __verify_base_and_local_md5 "$HOME"/.vimrc.bundles; then
    printf 'Vim bundles are being installed... '
    if command vim -u "$HOME"/.vimrc.bundles +'PlugInstall' +'qall' </dev/null &>/dev/null; then
      printf 'Done\n'
      __generate_base_and_local_md5 "$HOME"/.vimrc.bundles
    else
      printf 'ERROR\n'
      printf 'Encountered an error when running `%s`' "vim +'PlugInstall'" >&2
    fi
  fi

  printf 'Vim bundles are being updated... '
  if command vim -u "$HOME"/.vimrc.bundles +'PlugUpdate' +'PlugClean!' +'qall' </dev/null &>/dev/null; then
    printf 'Done\n'
  else
    printf 'ERROR\n'
    printf 'Encountered an error when running `%s`' "vim +'PlugUpdate'" >&2
  fi
fi

cat <<MSG
--------------------
>>  Done.
--------------------
MSG
