#!/usr/bin/env bash
set -euo pipefail

HOOK_DIR="${0%/*}/../"
source "${HOOK_DIR}/lib/base.sh"

__cleanup_broken_symlinks() {
  if is_mac; then
    find "${HOME}" -type l -not -path "${HOME}/Libraries/*" -and ! -exec test -e {} \; -delete 2>/dev/null || true
  else
    find "${HOME}" -xtype l -not -path "${HOME}/Libraries/*" -delete 2>/dev/null || true
  fi
}


if [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
  printf '%s\n' '-------------------------------------------------------'
  __message 'Cleanup'
  printf '%s\n' '-------------------------------------------------------'

  printf '>>  %s ... ' 'Cleaning up previous syncs from dotfiles repo'
  __cleanup_broken_symlinks
  printf '%s\n' 'Done'
fi
