#!/bin/bash
set -e

cat <<MSG

For security reasons, PGP keys are not able to automatically be imported. Please
do so manually by closing this terminal session, opening a new one, and running
the following:

    gpg --import [path to private key]

MSG


